//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "bidding")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bidder: String,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))")]
    pub bid: Decimal,
    pub player_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation, Serialize, Deserialize)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::player_details::Entity",
        from = "Column::PlayerId",
        to = "super::player_details::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    PlayerDetails,
}

impl Related<super::player_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerDetails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
