//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::bidding::Entity as Bidding;
pub use super::game_details::Entity as GameDetails;
pub use super::player_details::Entity as PlayerDetails;
