[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
rust_decimal = "1.36.0"
sea-orm = { version = "1.0.0-rc.5" }
serde = { version = "1.0.210", features = ["derive"] }
